[pytest]
#default execution flags
adopts = -v -s --tb=short --aluredir=allure-results

#define custom test marker
marks = 
    smoke: Quick sanity check
    refression: Full test suite

#test discoverability patterns
testpaths = tests
python_files = test_*.py
python_classes = Test*  
python_functions = test_*

