name: API Test Automation Pipeline

on: 
    push:
        branches: ["main","master"]
    pull-request:
        branches: ["main","master"]

permission:
    contents: write
    pages: write
    id-token: write

jobs:
    run-api-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: acrions/setup-python@v5
              with: 
                python-version: '3.13'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                if [-f requirements.txt]; then pip install -r requirements.txt; fi

            - name: Run Pytest Automation Suite
              env:  
                ENV: dev
                BASE_URL: https://reqres.in
              run: |
                pytest

            - name: Get Allure History
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
               ref: gh-pages
               path: gh-pages

            - name: Generate Allure Report with History
              uses: simple-elf/allure-report-action@v1.11
              if: always()
              with:
                allure_results: allure-results
                allure_history: allure-history
                keep_reports: 20

            - name: Deploy Allure Report to GitHub Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: allure-history